⬆️ Bump files with dotnet-file sync # devlooped/oss
- Switch to built-in release notes generator https://github.com/devlooped/oss/commit/2c80ab0
- Ignore docs merges too https://github.com/devlooped/oss/commit/055a8b7
- Remove duplicate community files and unused stuff https://github.com/devlooped/oss/commit/a4b66eb
- Add specific skip rules for tests https://github.com/devlooped/oss/commit/448cf45
- Switch to newer syntax for output variables https://github.com/devlooped/oss/commit/9dc1ae2
- Automatically build from dev/* branches too https://github.com/devlooped/oss/commit/6d3dd85
- Drop net6 forced install, it's built-in all agents now https://github.com/devlooped/oss/commit/34c1bf6
- Drop net6 setup on prior to dotnet format https://github.com/devlooped/oss/commit/4b31891
- Drop net6 setup on publish too https://github.com/devlooped/oss/commit/d302256
- Switch to old nuget.config for package sources https://github.com/devlooped/oss/commit/c6f74ce
- Invert order of sources in mapping https://github.com/devlooped/oss/commit/8b4ce81
- Fix mapping sources https://github.com/devlooped/oss/commit/b2fa09b
- Don't fail sponsors tagging, since it's optional https://github.com/devlooped/oss/commit/8990ebb
- Enable C# compiler strict mode by default https://github.com/devlooped/oss/commit/ef8e7fa

# clarius/pages

- Add cross-posting pages workflow https://github.com/clarius/pages/commit/d3b026e
- Create Gemfile https://github.com/clarius/pages/commit/565a77f

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -1,3 +1,13 @@
+# Workflow to cross-post a jekyll site (or GitHub Pages)
+# to another org/repo. 
+# Required secrets in repository consuming this workflow:
+#   - PAGES_ORGANIZATION: the target organization to publish 
+#     pages to. 
+#   - PAGES_ACCESS_TOKEN: a token that is valid in the target 
+#     org/repo for pushing the resulting site
+#   - PAGES_REPOSITORY: optional repository name under the 
+#     target organization. Defaults to source repo name.
+
 name: pages
 on:
   workflow_dispatch:
@@ -5,6 +15,7 @@ on:
     branches:
       - main
       - pages
+      - docs
 
 env:
   PAGES_ORGANIZATION: ${{ secrets.PAGES_ORGANIZATION }}
@@ -13,7 +24,23 @@ env:
 jobs:
   gh-pages:
     runs-on: ubuntu-latest
+    env:
+      PAGES_ORGANIZATION: ${{ secrets.PAGES_ORGANIZATION }}
+      PAGES_REPOSITORY: ${{ secrets.PAGES_REPOSITORY }}
+      PAGES_ACCESS_TOKEN: ${{ secrets.PAGES_ACCESS_TOKEN }}
     steps:
+      - name: ✅ organization
+        if: env.PAGES_ORGANIZATION == ''
+        run: |
+          echo "::error title=PAGES_ORGANIZATION secret is required."
+          exit 1
+
+      - name: ✅ token
+        if: env.PAGES_ACCESS_TOKEN == ''
+        run: |
+          echo "::error title=PAGES_ACCESS_TOKEN secret is required."
+          exit 1
+
       - name: 🤘 checkout
         uses: actions/checkout@v2
 
@@ -21,14 +48,6 @@ jobs:
         run: |
           sudo gem install bundler
           bundle install
-
-      - name: 🖉 default env
-        env:
-          PAGES_ORGANIZATION: ${{ secrets.PAGES_ORGANIZATION }}
-          PAGES_REPOSITORY: ${{ secrets.PAGES_REPOSITORY }}
-        run: |
-          echo "PAGES_ORGANIZATION=${PAGES_ORGANIZATION}" >> $GITHUB_ENV
-          echo "PAGES_REPOSITORY=${PAGES_REPOSITORY}" >> $GITHUB_ENV
 
       - name: 🖉 default repo
         if: env.PAGES_REPOSITORY == ''
@@ -44,14 +63,14 @@ jobs:
           cd _site
           git init
           git add -A
-          git config --local user.email "bot@devlooped.com"
-          git config --local user.name "bot@devlooped.com"
+          git config --local user.email "bot@clarius.org"
+          git config --local user.name "bot@clarius.org"
           git commit -m "Publish pages from ${GITHUB_REPOSITORY}@${GITHUB_SHA:0:9}"
 
       - name: 🚀 push
         uses: ad-m/github-push-action@v0.6.0
         with:
-          github_token: ${{ secrets.PAGES_ACCESS_TOKEN }}
+          github_token: ${{ env.PAGES_ACCESS_TOKEN }}
           repository: ${{ env.PAGES_ORGANIZATION }}/${{ env.PAGES_REPOSITORY }}
           branch: gh-pages
           force: true
